### PR TITLE
Add random jitter to exponential backoff time in MQTTAsync client

### PR DESCRIPTION
**Pull request by kellycampbell**
This makes exponential backoff times vary by +/- 20% in order to avoid clustered reconnect calls.
The second commit in this allows specifying connect retry intervals in milliseconds because we want to have the minimum interval be able to be less than 1 second.

### CODE REVIEW

**Comment by kellycampbell** [comment]
The CI failures look like they would be fixed by #214

**Comment by icraggs** [comment]
As it stands, this PR does not build on Windows (https://ci.appveyor.com/project/icraggs/paho-mqtt-c-t6duj):

MQTTAsync.c
C:\projects\paho-mqtt-c-t6duj\src\MQTTAsync.c(392): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
C:\projects\paho-mqtt-c-t6duj\src\MQTTAsync.c(393): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
C:\projects\paho-mqtt-c-t6duj\src\MQTTAsync.c(569): warning C4013: 'srandom' undefined; assuming extern returning int
C:\projects\paho-mqtt-c-t6duj\src\MQTTAsync.c(569): error C2224: left of '.tv_usec' must have struct/union type
C:\projects\paho-mqtt-c-t6duj\src\MQTTAsync.c(2341): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\projects\paho-mqtt-c-t6duj\src\MQTTAsync.c(2395): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
NMAKE : fatal error U1077: 'C:\PROGRA~2\MI0E91~1.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'

I'll look into it, unless you get there before I do.

**Comment by icraggs** [comment]
Superseded by #679
